# -*- coding: utf-8 -*-
"""kasir_sederhana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wI7LsBCKm5e60HFU7lue854TbBQuFAWg
"""

# Program Kasir Sederhana
print("=== PROGRAM KASIR TOKO SEDERHANA ===")

# Inisialisasi total harga
total_harga = 0

# Input harga untuk 3 barang
for i in range(1, 4):
    harga = float(input(f"Masukkan harga barang ke-{i}: Rp"))
    total_harga += harga  # Menambahkan harga ke total

# Menampilkan total pembayaran
print(f"\nTotal pembayaran: Rp{total_harga:,.2f}")