# -*- coding: utf-8 -*-
"""Rekursif_Faktorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKaEalFPLRoVSsiu93beIVLwIL3uIYwg
"""

def faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * faktorial(n - 1)

# Input dari pengguna
angka = int(input("Masukkan bilangan untuk dihitung faktorialnya: "))

# Memastikan input tidak negatif
if angka < 0:
    print("Faktorial tidak terdefinisi untuk bilangan negatif")
else:
    print(f"Faktorial dari {angka} adalah {faktorial(angka)}")