# -*- coding: utf-8 -*-
"""Sistem _Input_Nilai _Tertinggi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCKlVHi96Q6NE0vt5pdBUC7HAFkt-TWV
"""

# Inisialisasi list untuk menyimpan nilai siswa
nilai_siswa = []

# Input nilai untuk 5 siswa menggunakan perulangan
for i in range(5):
    nilai = float(input(f"Masukkan nilai siswa ke-{i+1}: "))
    nilai_siswa.append(nilai)

# Mencari nilai tertinggi dan indeksnya
nilai_tertinggi = max(nilai_siswa)
indeks_siswa = nilai_siswa.index(nilai_tertinggi) + 1  # +1 karena indeks dimulai dari 0

# Menampilkan hasil
print(f"Nilai tertinggi adalah {nilai_tertinggi} diperoleh oleh siswa ke-{indeks_siswa}")