# -*- coding: utf-8 -*-
"""Sistem_Diskon _E-commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQdQpEJfS0B6B_PqOWFi1cXjd694vO0l
"""

# Input total belanja
total_belanja = float(input("Masukkan total belanja: Rp"))

# Percabangan untuk menentukan diskon
if total_belanja > 500000:
    diskon = total_belanja * 0.1
    total_bayar = total_belanja - diskon
    print(f"Selamat! Anda mendapatkan diskon 10% sebesar Rp{diskon:,.2f}")
else:
    diskon = 0
    total_bayar = total_belanja
    print("Maaf, Anda belum memenuhi syarat untuk mendapatkan diskon")

# Menampilkan total yang harus dibayar
print(f"Total yang harus dibayar: Rp{total_bayar:,.2f}")