# -*- coding: utf-8 -*-
"""syarat_lulus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baZbNoPX_Dl3gBh6oncehqgthwqyvvdr
"""

# Program Penentuan Kelulusan Berdasarkan Rata-Rata Nilai
print("=== PROGRAM PENENTUAN KELULUSAN ===")

# Input nilai 3 mata pelajaran
nilai_mata_pelajaran = []
for i in range(1, 4):
    while True:
        try:
            nilai = float(input(f"Masukkan nilai mata pelajaran ke-{i}: "))
            if 0 <= nilai <= 100:
                nilai_mata_pelajaran.append(nilai)
                break
            else:
                print("Nilai harus antara 0-100. Silakan coba lagi.")
        except ValueError:
            print("Input tidak valid. Masukkan angka.")

# Hitung rata-rata
rata_rata = sum(nilai_mata_pelajaran) / len(nilai_mata_pelajaran)

# Tentukan status kelulusan
if rata_rata >= 75:
    status = "LULUS"
else:
    status = "TIDAK LULUS"

# Tampilkan hasil
print(f"\nRata-rata nilai: {rata_rata:.2f}")
print(f"Status: {status}")